{% set name = "xcmocean" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xcmocean-{{ version }}.tar.gz
  sha256: 7c55e1c0fcdea469c58331c25630e50e1d5ec0311581724f3e860c1a176cef9e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - cmocean
    - python >={{ python_min }}
    - xarray

test:
  imports:
    - xcmocean
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kthyng/xcmocean
  summary: Opinionated xarray accessor for choosing colormaps
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kthyng
